language: csharp
dist: trusty
compiler: gcc
dotnet: 2.0.0
mono: none

before_script:
  - openssl aes-256-cbc -K $encrypted_e86a7a1dbeca_key -iv $encrypted_e86a7a1dbeca_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
    
script:
  - set -e
  - scripts/detect_changes.sh
  - if [ -d tmp/gh-pages ]; then git -C tmp/gh-pages push origin gh-pages; fi
